package com.Transitops.Spring_project.service;

import com.Transitops.Spring_project.dto.CreateExpenseRequest;
import com.Transitops.Spring_project.dto.ExpenseResponse;
import com.Transitops.Spring_project.dto.FinanceSummaryResponse;
import com.Transitops.Spring_project.model.*;
import com.Transitops.Spring_project.repository.ExpenseRecordRepository;
import com.Transitops.Spring_project.repository.FuelLogRepository;
import com.Transitops.Spring_project.repository.TripRepository;
import com.Transitops.Spring_project.repository.VehicleRepository;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.math.BigDecimal;
import java.util.List;

@Service
public class ExpenseService {

    private final ExpenseRecordRepository expenseRecordRepository;
    private final FuelLogRepository fuelLogRepository;
    private final VehicleRepository vehicleRepository;
    private final TripRepository tripRepository;

    public ExpenseService(
            ExpenseRecordRepository expenseRecordRepository,
            FuelLogRepository fuelLogRepository,
            VehicleRepository vehicleRepository,
            TripRepository tripRepository) {
        this.expenseRecordRepository = expenseRecordRepository;
        this.fuelLogRepository = fuelLogRepository;
        this.vehicleRepository = vehicleRepository;
        this.tripRepository = tripRepository;
    }

  // MANUAL: Financial Analyst adds toll/other expense
    @Transactional
    public ExpenseResponse createExpense(CreateExpenseRequest request) {
        Vehicle vehicle = vehicleRepository.findById(request.getVehicleId())
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.BAD_REQUEST, "Vehicle not found"));

        BigDecimal tollFee = request.getTollFee() != null
                ? request.getTollFee() : BigDecimal.ZERO;
        BigDecimal otherFee = request.getOtherFee() != null
                ? request.getOtherFee() : BigDecimal.ZERO;

        if (tollFee.compareTo(BigDecimal.ZERO) <= 0
                && otherFee.compareTo(BigDecimal.ZERO) <= 0) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST,
                    "Enter toll fee or other fee (at least one must be greater than 0)");
        }

        Trip trip = null;
        if (request.getTripId() != null) {
            trip = tripRepository.findById(request.getTripId())
                    .orElseThrow(() -> new ResponseStatusException(
                            HttpStatus.BAD_REQUEST, "Trip not found"));
        }

        ExpenseRecord record = ExpenseRecord.builder()
                .trip(trip)
                .vehicle(vehicle)
                .tollFee(tollFee)
                .otherFee(otherFee)
                .maintenanceLinkedCost(BigDecimal.ZERO)
                .status(ExpenseStatus.AVAILABLE)
                .autoGeneratedFromMaintenance(false)
                .build();

        expenseRecordRepository.save(record);
        return toResponse(record, "Expense created successfully");
    }

    // AUTO: called when Fleet Manager adds maintenance
    @Transactional
    public void createFromMaintenance(MaintenanceRecord maintenance) {
        if (expenseRecordRepository.existsByMaintenanceRecordId(maintenance.getId())) {
            return;
        }

        ExpenseRecord record = ExpenseRecord.builder()
                .vehicle(maintenance.getVehicle())
                .maintenanceRecord(maintenance)
                .maintenanceLinkedCost(maintenance.getCost())
                .tollFee(BigDecimal.ZERO)
                .otherFee(BigDecimal.ZERO)
                .status(ExpenseStatus.AVAILABLE)
                .autoGeneratedFromMaintenance(true)
                .build();

        expenseRecordRepository.save(record);
    }

    @Transactional(readOnly = true)
    public List<ExpenseResponse> getAllExpenses() {
        return expenseRecordRepository.findAll()
                .stream()
                .map(r -> toResponse(r, null))
                .toList();
    }

    @Transactional
    public ExpenseResponse completeExpense(Long id) {
        ExpenseRecord record = expenseRecordRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "Expense record not found"));

        if (record.getStatus() == ExpenseStatus.COMPLETED) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST, "Expense is already completed");
        }

        record.setStatus(ExpenseStatus.COMPLETED);
        return toResponse(record, "Expense marked as completed");
    }

    @Transactional(readOnly = true)
    public FinanceSummaryResponse getFinanceSummary() {
        BigDecimal totalFuelCost = fuelLogRepository.findAll()
                .stream()
                .map(FuelLog::getFuelCost)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        BigDecimal totalMaintenanceCost = BigDecimal.ZERO;
        BigDecimal totalTollFees = BigDecimal.ZERO;
        BigDecimal totalOtherFees = BigDecimal.ZERO;

        for (ExpenseRecord record : expenseRecordRepository.findAll()) {
            totalMaintenanceCost = totalMaintenanceCost.add(record.getMaintenanceLinkedCost());
            totalTollFees = totalTollFees.add(record.getTollFee());
            totalOtherFees = totalOtherFees.add(record.getOtherFee());
        }

        BigDecimal totalOperationalCost = totalFuelCost
                .add(totalMaintenanceCost)
                .add(totalTollFees)
                .add(totalOtherFees);

        return FinanceSummaryResponse.builder()
                .totalFuelCost(totalFuelCost)
                .totalMaintenanceCost(totalMaintenanceCost)
                .totalTollFees(totalTollFees)
                .totalOtherFees(totalOtherFees)
                .totalOperationalCost(totalOperationalCost)
                .build();
    }

    private ExpenseResponse toResponse(ExpenseRecord record, String message) {
        Vehicle vehicle = record.getVehicle();
        Trip trip = record.getTrip();

        BigDecimal total = record.getTollFee()
                .add(record.getOtherFee())
                .add(record.getMaintenanceLinkedCost());

        return ExpenseResponse.builder()
                .id(record.getId())
                .tripId(trip != null ? trip.getId() : null)
                .tripLabel(buildTripLabel(trip))
                .vehicleId(vehicle.getId())
                .vehicleRegistrationNumber(vehicle.getRegistrationNumber())
                .tollFee(record.getTollFee())
                .otherFee(record.getOtherFee())
                .maintenanceLinkedCost(record.getMaintenanceLinkedCost())
                .total(total)
                .status(record.getStatus())
                .autoGeneratedFromMaintenance(record.isAutoGeneratedFromMaintenance())
                .message(message)
                .build();
    }

    private String buildTripLabel(Trip trip) {
        if (trip == null) {
            return null;
        }
        return trip.getSource() + " → " + trip.getDestination();
    }
}