spring:
  application:
    name: Spring-project
  datasource:
    url: jdbc:h2:mem:transitops
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: transitops-super-secret-key-change-in-production-min-32-chars
  expiration-ms: 86400000

server:
  port: 8080