import { authFetch } from './apiClient'

export const EXPENSE_STATUS_LABELS = {
  AVAILABLE: 'Open',
  COMPLETED: 'Completed',
}

function mapExpenseFromApi(expense) {
  return {
    id: expense.id,
    tripId: expense.tripId,
    tripLabel: expense.tripLabel,
    vehicleId: expense.vehicleId,
    vehicleRegistrationNo: expense.vehicleRegistrationNumber,
    tollFee: expense.tollFee,
    otherFee: expense.otherFee,
    maintenanceLinkedCost: expense.maintenanceLinkedCost,
    total: expense.total,
    status: expense.status,
    autoGeneratedFromMaintenance: expense.autoGeneratedFromMaintenance,
  }
}

export function getExpenseStatusLabel(status) {
  return EXPENSE_STATUS_LABELS[status] || status
}

export async function createExpense(expenseData) {
  const response = await authFetch('/api/expenses', {
    method: 'POST',
    body: JSON.stringify({
      vehicleId: Number(expenseData.vehicleId),
      tripId: expenseData.tripId ? Number(expenseData.tripId) : null,
      tollFee: Number(expenseData.tollFee || 0),
      otherFee: Number(expenseData.otherFee || 0),
    }),
  })

  return mapExpenseFromApi(response)
}

export async function getExpenses() {
  const expenses = await authFetch('/api/expenses')
  return expenses.map(mapExpenseFromApi)
}

export async function completeExpense(id) {
  const response = await authFetch(`/api/expenses/${id}/complete`, {
    method: 'PATCH',
  })

  return mapExpenseFromApi(response)
}