package com.Transitops.Spring_project.model;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "expense_records")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class ExpenseRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trip_id")
    private Trip trip;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vehicle_id", nullable = false)
    private Vehicle vehicle;

    @Builder.Default
    private BigDecimal tollFee = BigDecimal.ZERO;

    @Builder.Default
    private BigDecimal otherFee = BigDecimal.ZERO;

    @Builder.Default
    private BigDecimal maintenanceLinkedCost = BigDecimal.ZERO;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "maintenance_record_id")
    private MaintenanceRecord maintenanceRecord;

    @Enumerated(EnumType.STRING)
    @Builder.Default
    private ExpenseStatus status = ExpenseStatus.AVAILABLE;

    @Builder.Default
    private boolean autoGeneratedFromMaintenance = false;

    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}