package com.Transitops.Spring_project.dto;

import com.Transitops.Spring_project.model.ExpenseStatus;
import lombok.Builder;
import lombok.Data;
import java.math.BigDecimal;

@Data
@Builder
public class ExpenseResponse {
    private Long id;
    private Long tripId;
    private String tripLabel;
    private Long vehicleId;
    private String vehicleRegistrationNumber;
    private BigDecimal tollFee;
    private BigDecimal otherFee;
    private BigDecimal maintenanceLinkedCost;
    private BigDecimal total;
    private ExpenseStatus status;
    private boolean autoGeneratedFromMaintenance;
    private String message;
}